name: happyland-revenue
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - streamlit=1.32.0
  - pandas=2.1.4
  - numpy=1.26.4
  - scikit-learn=1.3.2
  - openpyxl=3.1.2
  - pip:
    - plotly==5.17.0
